### ISSUE TITLE
The following sdk11 link is invalid

### ISSUE THREAD

**Issue by arinhouck** [InstantClientTap/homebrew-instantclient#10]
```
http://download.oracle.com/otn/mac/instantclient/11204/instantclient-sdk-macos.x64-11.2.0.4.0.zip
```

The above link no longer works from oracle.

**Comment by kaukas** [comment]
I just tried it and it worked. Please accept the licence terms on http://www.oracle.com/technetwork/topics/intel-macsoft-096467.html and then try the link again.

**Comment by kaukas** [comment]
I am closing this bug report for now. Please reopen if it is still an issue. Thank you!
