### ISSUE TITLE
Installing ROracle

### ISSUE THREAD

**Issue by dalloliogm** [InstantClientTap/homebrew-instantclient#11]
Hello,
thank you for writing these recipes.

The installation of the InstantClient worked correctly, but now I would like to install [ROracle](https://cran.r-project.org/web/packages/ROracle/index.html) (R package for accessing Oracle using instanclient), but I am not sure how to set up the flags.

This are the install instructions: https://cran.r-project.org/web/packages/ROracle/INSTALL

I've tried with all the combinations of LD_LIBRARY_PATH (e.g. adding .linuxbrew/Cellar/instantclient-sdk/12.1.0.2.0/lib/), but none of them worked. I always get the error:

```
$ R CMD INSTALL ROracle_1.1-1.tar.gz
normal, x[x<0], x[x>=0], 19/01/2038 03:14:07,
"string", NA/NaN/NULL, FALSE, TRUE, Inf, stderror, warn, error.
* installing to library ‘/home/user/linuxbrew/lib/R/3.3/site-library’
* installing *source* package ‘ROracle’ ...
** package ‘ROracle’ successfully unpacked and MD5 sums checked
configure: error: OCI headers not found
ERROR: configuration failed for package ‘ROracle’
* removing ‘/home/user/linuxbrew/lib/R/3.3/site-library/ROracle’

```

**Comment by cmgiven** [comment]
ROracle assumes that the SDK is installed in the same directory as the Basic package. The following worked for me (note that I'm on a Mac, and that I'm using basiclite):

``` sh
export LD_LIBRARY_PATH=/usr/local/Cellar/instantclient-basiclite/12.1.0.2.0/lib:$LD_LIBRARY_PATH
R CMD INSTALL --configure-args='--with-oci-lib=/usr/local/Cellar/instantclient-basiclite/12.1.0.2.0/lib --with-oci-inc=/usr/local/Cellar/instantclient-sdk/12.1.0.2.0/lib/sdk/include' ROracle_1.2-2.tar.gz
```

**Comment by kaukas** [comment]
Sorry but I do not have any input on this since I have never used ROracle myself. Should I extend the README with your remarks?

**Comment by kaukas** [comment]
I am closing this issue for now. Please reopen if you have any more input.

Thank you!
