### ISSUE TITLE
Issue installing instantclient-basic

### ISSUE THREAD

**Issue by kingdonb** [InstantClientTap/homebrew-instantclient#15]
Hello,

I have been using the instantclient tap successfully with ruby-oci8 gem for a while, and just got this report during brew upgrade:

```
 brew install InstantClientTap/instantclient/instantclient-basic
==> Installing instantclient-basic from instantclienttap/instantclient
==> Downloading http://download.oracle.com/otn/mac/instantclient/122010/instantclient-basic-macos.x64-12.2.0.1.0.zip
Already downloaded: /Users/kingdonb/Library/Caches/Homebrew/instantclient-basic-macos.x64-12.2.0.1.0.zip
Error: File exists @ syserr_fail2_in - libclntsh.dylib
```

I have tried to remove all of the related libraries (`instantclient-{basic,sqlplus,sdk}`) and I get this error with only instantclient-basic.  Is there an error in this?  If you can you reproduce the issue, I'd love to know the solution as I have little understanding of how homebrew works.  If you cannot, I'll be glad to provide more information!

Thanks

**Comment by naroah** [comment]
I've encountered the same issue. Checked the instantclient-basic zip file, oracle provided the symbolic link [ libclntsh.dylib and libocci.dylib ] already. So we do not need the "ln_s dylib" in the formula for Oracle instant client 12.2.

**Comment by kaukas** [comment]
Please try the latest version.

Thank you!

**Comment by kingdonb** [comment]
Thanks!  Solved
