### ISSUE TITLE
When installing php --with-pdo-oci: oci.h file not found

### ISSUE THREAD

**Issue by plashenkov** [InstantClientTap/homebrew-instantclient#16]
Hello!

When trying to install `php --with-pdo-oci` we get the following error:

```
ext/pdo_oci/php_pdo_oci_int.h:21:10: fatal error: 'oci.h' file not found
```

I guess this is due when we install `instantclient-sdk`, the installation script does not copy *.h files into `/usr/local/include/` folder. Shouldn't it do that?

**Comment by plashenkov** [comment]
I.e., more precisely, script should `ln` all `*.h` files from a directory where SDK is installed to the `/usr/local/include/` folder. Am I right?

**Comment by kaukas** [comment]
Yes, perhaps. Please try the [header-file-links](https://github.com/InstantClientTap/homebrew-instantclient/tree/header-file-links) branch.

**Comment by kaukas** [comment]
The branch has been merged to `master`, I hope that does not cause trouble to anyone. Please let me know if it does or if it still does not work in your particular case.
