### ISSUE TITLE
Why does sqlplus conflict with basiclite?

### ISSUE THREAD

**Issue by rmx90210** [InstantClientTap/homebrew-instantclient#20]
First of all, this is an awesome project, thanks for making this easier!

I wanted to install `basiclite` and `sqlplus`. I downloaded the files and put them in my cache. `basiclite` installed fine, but `sqlplus` threw an error:

```
Error: Cannot install instantclienttap/instantclient/instantclient-basic because conflicting formulae are installed.
  instantclient-basiclite

Please `brew unlink instantclient-basiclite` before continuing.
```

Does `sqlplus` only work with `basic` for some reason?

**Comment by kaukas** [comment]
Please try

```sh
$ brew install instantclient-sqlplus --with-basiclite
```

and let me know if that works.

**Comment by rmx90210** [comment]
That worked, thanks Linas!

**Comment by kaukas** [comment]
Welcome! :-)
