### ISSUE TITLE
feature request: formula for ODBC package

### ISSUE THREAD

**Issue by copernican** [InstantClientTap/homebrew-instantclient#21]
Thanks for this helpful tap. Has there been any consideration of adding the Instant Client ODBC package? I routinely connect to Oracle Database via ODBC, so this would be very helpful.

**Comment by kaukas** [comment]
Hello.

I have never used the ODBC package myself so I would not even know how to test it. Would you be able to propose a PR?

Thank you!

**Comment by copernican** [comment]
The contents of the ODBC package can be separated into three parts:

1. the ODBC driver: `libsqora.dylib.12.1`
2. a setup script: `odbc_update_ini.sh`
3. help files 

The ODBC driver is the essential component required to configure an ODBC connection to Oracle Database, e.g., using unixODBC. The setup script creates two files:

1. the ODBC driver configuration file `odbcinst.ini`, which by default goes into `/usr/local/etc`
2. the data source configuration file `odbc.ini`, which by default goes into `~` (as `.odbc.ini`)

The key thing is to install the ODBC driver `libsqora.dylib.12.1`, presumably into `/usr/local/Cellar/instantclient-odbc`, and then symlink it into `/usr/local/lib`. There are [issues](https://blogs.oracle.com/opal/installing-the-oracle-odbc-driver-on-macos?dd) with the setup script, so I would propose not installing/running it at all, and requiring that the user configure `odbcinst.ini` and `odbc.ini`.

So, essentially, the only thing that the formula would need to do is copy `libsqora.dylib.12.1` from the zip file into the appropriate location in `/usr/local/Cellar`, and then symlink it into `/usr/local/lib`. The user would then need to set up the ODBC driver and data sources on their own.

Does this make sense? I've never written any Ruby, but I can try to adapt an existing formula for a PR if helpful.

**Comment by kaukas** [comment]
Thank you for all this information! Unfortunately, I don't have time for this right now. But if you could prepare a PR mimicking the other formulas I would consider merging it.
