### ISSUE TITLE
Formula for tools package

### ISSUE THREAD

**Issue by giacgbj** [InstantClientTap/homebrew-instantclient#22]
I mean http://download.oracle.com/otn/mac/instantclient/122010/instantclient-tools-macos.x64-12.2.0.1.0-2.zip .

It's useful at least for the command sqlldr which allows to load files into the db.

**Comment by kaukas** [comment]
I would consider merging a PR if you could prepare one mimicking the existing ones.

**Comment by meezaan** [comment]
@kaukas I've created a PR for this - https://github.com/InstantClientTap/homebrew-instantclient/pull/23.

**Comment by kaukas** [comment]
Thank you for the contribution, @meezaan!
