### ISSUE TITLE
brew 1.7.2 breaks `CacheWoDownloadStrategy`

### ISSUE THREAD

**Issue by soberstadt** [InstantClientTap/homebrew-instantclient#25]
Brew recently updated their `CurlDownloadStrategy` class that doesn't use a `@tarball_path` instance var.

In the meantime I duplicated the files to to match the new caching file name expectation.

Example: `cp -a instantclient-sdk-macos.x64-12.2.0.1.0-2.zip instantclient-sdk--12.2.0.1.0-2.zip`

**Comment by soberstadt** [comment]
cc @knutsenm

**Comment by jiahuang** [comment]
Just ran into this. I also tried doing this with symlinks like the docs suggest, but that didn't work and I had to move both copies of the zip to the homebrew cache dir.

**Comment by soberstadt** [comment]
@jiahuang I hope this issue report at least saved you a few minutes of debugging like what we had to do. Hopefully this tap can be updated ASAP.

**Comment by kaukas** [comment]
I pushed a change, hopefully it will fix the problem. Please follow the instructions from the `brew install instantclient-...` and let me know if they work.

**Comment by jiahuang** [comment]
@kaukas I uninstalled and tried out the new instructions. Ran into two issues:

1. The `~/Caches/Homebrew/downloads` folder doesn't exist for me by default
2. After making the folder, the instructions for the filename is too long: 

```
An example command to rename and move the file into the homebrew cache:

  $ cd /path/to/downloads && mv instantclient-sdk-macos.x64-12.2.0.1.0-2.zip /Users/jia/Library/Caches/Homebrew/downloads/61971ac46afc5676ed29559867a213dd92abb6469a5c584ab90588fa5df275cb--Site2pstoreToken=v1.2~EC062A1473FF0629A4~46406B34B99E9DB92735332032D89543537E72CB455CD37FFD1EF4D7ADD5F84DCA84ED76EA5CCF4577D883FFC97907452B1E43B4257AEF358451E06D6AE4DB6D0F0C04E7DE0B4E7294EE767AF206430AB9B48C00BFF333158C51782A7ACC8560A9E5BE8BCFACA0228E62B600FFD9D5D15130B00626F8648106588DC9393501D6C96EC219B74A0F528988FC9200BBD2DC65DA10EE7C06ACDC24B0556B0286A6292A2C5811635C4844CF5ED05158C7D4F911ED86AED6841FD90E3330FB26A61D52B9B9B894A63EAD758DE511F23BD4386F86281725BD9837C61CE6DE6D5C0B6AD1F6D48153681A23033FEE6E75B2AE469FA01C0A53EF51E59ED2014FB6FD4ECE6CAEBC5151738BE77B74F7A9ADC7366CD03201905EFA85C756
```

Gave me a `File name too long` error.

**Comment by jiahuang** [comment]
Seems like the [cached filename](https://github.com/Homebrew/brew/blob/662c1fab564602ead8bb724ff511d338ba1cc545/Library/Homebrew/download_strategy.rb#L205) that brew is looking for is

```
HOMEBREW_CACHE/"downloads/#{url_sha256}--*"
```

So doing something like `mv instantclient-sdk-macos.x64-12.2.0.1.0-2.zip ~/Caches/Homebrew/downloads/61971ac46afc5676ed29559867a213dd92abb6469a5c584ab90588fa5df275cb--` worked

I think the output of `cached_location` [appends something big in `resolved_basename`](https://github.com/Homebrew/brew/blob/662c1fab564602ead8bb724ff511d338ba1cc545/Library/Homebrew/download_strategy.rb#L211) if the cached file isn't found in downloads.

**Comment by kaukas** [comment]
I am lost. Homebrew keeps changing the meaning of their (public!) download strategy functions. Things worked a few days ago when I made a fix, now they are broken again. 😞

I'll see what I can do.

**Comment by kaukas** [comment]
So it turns out the CURL download strategy started making requests [outside its `fetch` method](https://github.com/Homebrew/brew/commit/fbcaa8c85ae42f127fd94a5d82f86a3eafb34848#diff-ad9201cdd3b6f948345629ad812cd5bdR326) to decide on the filename. Perhaps you can see why it is not a great idea in this case.

Switched to the `AbstractFileDownloadStrategy` (parent of the `CurlDownloadStrategy`). Should have used that in the first place.

The instructions should work again. Please try them out.

**Comment by kencheeto** [comment]
I ran into this as well today, I followed the brew install instructions to copy & prefix the downloaded zips to ~/Library/Caches/Homebrew/downloads and that worked.

**Comment by kaukas** [comment]
@kencheeto, could you please clarify if the instructions (as printed by `brew install ...`) were correct and worked or something is still wrong?

**Comment by kencheeto** [comment]
@kaukas the symlinking didn't work:

```
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `write': Broken pipe (Errno::EPIPE)
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `puts'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `rescue in block (3 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:31:in `block (3 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:30:in `fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:30:in `block (2 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:27:in `open'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:27:in `block in safe_fork'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:26:in `safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:719:in `build'
	from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:311:in `install'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:321:in `install_formula'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:253:in `block in install'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:251:in `each'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:251:in `install'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: An exception occured within a build process:
  SystemExit: exit
```

but copying the file using this instruction from `brew install ...` worked:

```
An example command to rename and move the file into the homebrew cache:

  $ cd /path/to/downloads && mv instantclient-basic-macos.x64-12.2.0.1.0-2.zip /Users/kencheeto/Library/Caches/Homebrew/downloads/665aa2952dd4fcdbbe25f6a02ee3cc8cf5b39ab36c8001447b303fe567cc8354--instantclient-basic-macos.x64-12.2.0.1.0-2.zip
```

**Comment by kaukas** [comment]
I tested symlinking just now and it worked without a problem. Please let me know if you have issues. Closing meanwhile.
