### ISSUE TITLE
After install I can't run the expdp tool

### ISSUE THREAD

**Issue by oscarsan** [InstantClientTap/homebrew-instantclient#38]
I get error

dyld: Library not loaded: @rpath/libclntsh.dylib.19.1
  Referenced from: /usr/local/bin/expdp
  Reason: image not found
[1]    61611 abort      expdp

**Comment by kaukas** [comment]
Works for me.

Which version of MacOS are you on? If Catalina or higher then you might need to set `DYLD_LIBRARY_PATH=$HOMEBREW_PREFIX/lib`. Let me know if that helps.

**Comment by oscarsan** [comment]
Hi, running Catalina, got it working but it is a misterius, my  HOMEBREW_PREFIX was empty, and this is in 2 different macs, I put it in usr/local and then set the DYLD_LIBRARY_PATH. Thanks.

➜  ~ export HOMEBREW_PREFIX="/usr/local"
➜  ~ $HOMEBREW_BREW_FILE
➜  ~ export DYLD_LIBRARY_PATH=$HOMEBREW_PREFIX/lib
➜  ~ echo $DYLD_LIBRARY_PATH
/usr/local/lib
➜  ~ expdp

Export: Release 19.0.0.0.0 - Production on Fri Feb 19 09:57:38 2021
Version 19.8.0.0.0

**Comment by kaukas** [comment]
I do not think you're the only one to hit this problem on Catalina+.

**Comment by kaukas** [comment]
Could you please try the branch `tools-on-catalina`? If it works I will merge it into master.

Sorry about the `HOMEBREW_PREFIX`, it's a placeholder, not supposed to be set normally.

**Comment by oscarsan** [comment]
Hi, how do you usually install a brew formula from a branch. Been trying unsuccessfully brew tap-new..

**Comment by kaukas** [comment]
Don't know what the official way is. If you have [hub](https://github.com/github/hub) then try this:
```bash
cd /usr/local/Homebrew/Library/Taps/instantclienttap/homebrew-instantclient # or wherever your brew is
hub checkout https://github.com/InstantClientTap/homebrew-instantclient/pull/39
brew install instantclient-tools
# test test test
brew uninstall instantclient-tools
git checkout master # back to normal
```

**Comment by oscarsan** [comment]
Ok, I can confirm this works.

**Comment by kaukas** [comment]
Closed by https://github.com/InstantClientTap/homebrew-instantclient/pull/39.
