### ISSUE TITLE
Use Homebrew to set a cookie?

### ISSUE THREAD

**Issue by craibuc** [InstantClientTap/homebrew-instantclient#4]
Can Homebrew set a cookie?  If so, perhaps you could follow the logic that Scoop's [oraclejdk](https://github.com/lukesampson/scoop-extras/blob/master/oraclejdk.json) package uses; essentially set the `oraclelicense` to `accept-securebackup-cookie`.

**Comment by kaukas** [comment]
I understand that OracleJDK only needs an accepted licence to allow a download. InstantClient however needs the user to be signed in in addition to the licence. In other words, I have not found a combination of cookies to give access to the files.

Are there any suggestions?

**Comment by craibuc** [comment]
Sorry, I guess that I forgot about that.

What if the formula an option that assumed that the credentials had been provided (user supplied values at https://login.oracle.com/mysso/signon.jsp which sets the required auth cookies).  If so, sending a POST to http://www.oracle.com/technetwork/topics/intel-macsoft-096467.html with form element of `oraclelicense` set to `accept-ic_macosx-cookie`, generates the various ZIP files' URLs.

To perform authentication, these form elements need to be set: `sso_username`, `ssopassword`, `locale`, `v`, `request_id`, `OAM_REQ`, `site2pstoretoken`.  I suppose you could prompt for the first two (which assumes that you've created an Oracle account), but you'd have to issue a GET request to http://www.oracle.com/technetwork/topics/intel-macsoft-096467.html to get the current values of the other elements.

**Comment by kaukas** [comment]
I would hesitate to merge such a change in even if someone made a PR for it. There would be a lot of flaky logic involved in my opinion.

**Comment by kaukas** [comment]
Oracle makes it complicated to install the packages automatically. I do not want to hack around that fact. Any code that tries to will probably end up being complex and unstable. Let's instead nag Oracle to simplify file downloads.

Closing this issue until there are better ideas.
