### ISSUE TITLE
network/admin setup

### ISSUE THREAD

**Issue by tadasvu** [InstantClientTap/homebrew-instantclient#40]
hey,

great stuff!

any ideas on what is the right path after installing instant client to setup configuration of ldap.ora and tnsnames.ora to be resolved from?
Should it be any path exported with ORACLE_HOME variable ? Can't locate network/admin folder anywhere.

Br,
Tadas

**Comment by kaukas** [comment]
Hi. I do not use this myself anymore. However, when I did it used to work out of the box, no ORACLE_HOME needed. I am sorry for not being able to provide useful info.

**Comment by mikealbert** [comment]
@tadasvu Setting `TNS_ADMIN` to the location of my tnsnames.ora worked for me.
