### ISSUE TITLE
Please add instant client 11.2 option

### ISSUE THREAD

**Issue by elbosp** [InstantClientTap/homebrew-instantclient#42]
Instant client 19.8 cannot be use for old oracle such as 9i.
Please consider add option for instant client 11.2

**Comment by kaukas** [comment]
We did support 11 in the past. You can either pin the brew tap to https://github.com/InstantClientTap/homebrew-instantclient/commit/e8c17c2e2b8b551bd416da03ef55478a6419b387 or fork this repo and roll back to that old version.
